### PR TITLE
Fix mardown

### PR DESCRIPTION
**Pull request by wilbertom**
The markdown wasn't letting me work on other stuff and had to fix it. Also had to rename the sheets on the  spreadsheet because the template was using the wrong names. Seemed easier than refactoring the template. 

Example: renamed investigate to investigation.

I think the markdown was wrong because Text Edit was used to edit the content. Never use `Text Edit` because it changes `'` to some prettier version and changes `-` to something thicker.

### CODE REVIEW

**Comment by bepetersn** [comment]
Hey Wil,

I hit the same problems with the Markdown, pretty sure. I wasn't confident
if it was a weird text editor used to edit them or not, but the problem was
really a UnicodeDecodeError. I was able to fix it to ensure those kinds of
errors didn't crop up by messing with the code inside the `read_file`
function. How did you get around it? Did you just edit out the weird
symbols?

At any rate, thanks for working on that. I avoided the issue when I
realized I was getting a weird issue, and wanted to have something looking
good on the website today. My temporary solution was to rollback using the
markdown files to load in the content (we were using a spreadsheet before),
and made sure those came out looking OK. These changes are on the sc3
branch "content-from-spread".

Like I said, thanks for pushing ahead. However, changing the sheet names
was intentional on my part (I pushed the changes to the templates in my
branch). If you want, could you just do a replace-search to update the
templates to have the spreadsheet names I had before, e.g.:

"investigation -> investigate"

This is what we want eventually, anyway.

On Tue, Feb 11, 2014 at 7:18 AM, Wilberto Morales
notifications@github.comwrote:

> The markdown wasn't letting me work on other stuff and had to fix it. Also
> had to rename the sheets on the spreadsheet because the template was using
> the wrong names. Seemed easier than refactoring the template.
> 
> Example: renamed investigate to investigation.
> 
> I think the markdown was wrong because Text Edit was used to edit the
> content. Never use Text Edit because it changes ' to some prettier
> 
> ## version and changes - to something thicker.
> 
> You can merge this Pull Request by running
> 
>   git pull https://github.com/wilbertom/chicago-justice simple-dropdown
> 
> Or view, comment on, or merge it at:
> 
>   https://github.com/sc3/chicago-justice/pull/53
> Commit Summary
> - Fix markdown
> - Remove, duplicate? content
> 
> File Changes
> - _M_ content/court_rail.mdhttps://github.com/sc3/chicago-justice/pull/53/files#diff-0(2)
> - _M_ content/investigate.mdhttps://github.com/sc3/chicago-justice/pull/53/files#diff-1(36)
> - _M_ content/investigate_rail.mdhttps://github.com/sc3/chicago-justice/pull/53/files#diff-2(2)
> - _M_ content/jail_rail.mdhttps://github.com/sc3/chicago-justice/pull/53/files#diff-3(2)
> - _M_ content/prosecute.mdhttps://github.com/sc3/chicago-justice/pull/53/files#diff-4(4)
> - _M_ content/prosecute_rail.mdhttps://github.com/sc3/chicago-justice/pull/53/files#diff-5(2)
> - _M_ content/report.mdhttps://github.com/sc3/chicago-justice/pull/53/files#diff-6(2)
> 
> Patch Links:
> - https://github.com/sc3/chicago-justice/pull/53.patch
> - https://github.com/sc3/chicago-justice/pull/53.diff
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/chicago-justice/pull/53
> .

## 

Brian Peterson

**Comment by wilbertom** [comment]
The names on the sheet are back to the way they are going to be used. And I replaced the bad characters on the content files(the weird symbols). If the spreadsheet is giving problems, maybe try using the values on my content directory.

**Comment by bepetersn** [comment]
Did you fix the sheet names that are referenced in the template, then, too?

**Comment by wilbertom** [comment]
No, I thought the other branch had that fixed? I can do it right now if needed.

**Comment by bepetersn** [comment]
Oh, it does, and we should merge the two branches together. I only created
the other branch as a temporary patch.

If you switch the names back in the spreadsheet, but not in the templates,
you will get errors when you try to preview your work. If you could fix it,
that'd be cool.

**Comment by bepetersn** [comment]
I am including you in this conversion so you can see what's going on, Sarah.

**Comment by wilbertom** [comment]
Ok fixing it right now.

**Comment by bepetersn** [comment]
Thanks for excising the weird symbols as was necessary to get rid of unicode errors, @wilbertom, that would have been annoying to figure out exactly; thanks to both you and @sarahelizabeth for in-lining the content from the markdown files; and thanks again to Sarah for transcribing all of the spreadsheet content into those files.

**Pull request merged**
