### PR TITLE
First proposed method for templating.

### PR DESCRIPTION
**Pull request by wilbertom**
This is a proposition to do client side templating. If this doesn't work, I can do it on the server side.

### CODE REVIEW

**Comment by bepetersn** [comment]
I managed to get a first pass at simplifying our templating without using underscore and creating too much new work for us, this was with commit 876ef8. I made a lot of changes with that commit, but mostly they involved backing off of representing each individual slide in the app's state. 

The changes that actually added functionality were mostly in SlideView.js, where I just used a bit of Jquery and simplified a lot of things. There are still issues... the main one is a notable inefficiency created by the new system: we now do a GET request for the correct stage's html page each time a slide is loaded, which is unnecessary. But I think it will work, at least for now, in the interest of getting this project done on deadline.

**Comment by bepetersn** [comment]
Thanks for the work you did on this, Wil. You gave me at least some good ideas, and helped me otherwise too.

**Comment by eads** [comment]
I can review this tonight I hope. I have a strong idea of how to do it.

Given that you aren't serving that much data per Ajax call I think your
inefficiency isn't too much of a worry.

**Comment by bepetersn** [comment]
Well, the data isn't the issue. It's just the fact that your computer
actually makes a distinct GET request over the internet. That takes time no
matter what the payload, I think.

On Tue, Dec 10, 2013 at 9:08 AM, David Eads notifications@github.comwrote:

> I can review this tonight I hope. I have a strong idea of how to do it.
> 
> Given that you aren't serving that much data per Ajax call I think your
> inefficiency isn't too much of a worry.
> On Dec 10, 2013 5:44 AM, "Brian Everett Peterson" <
> notifications@github.com>
> wrote:
> 
> > Closed #30 https://github.com/bepetersn/chicago-justice/pull/30.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/bepetersn/chicago-justice/pull/30>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/bepetersn/chicago-justice/pull/30#issuecomment-30234679
> .

## 

Brian Peterson

**Comment by eads** [comment]
It's true you're network-bound at that point. But on a low-latency
connection, this can be _very_ fast -- think about how fast Google's
autocomplete works.

**Pull request closed without merging**
