### PR TITLE
Chart macro draft 1

### PR DESCRIPTION
**Pull request by wilbertom**
Hey Crew, I think this is a decent way to template the chart. @eads can you review this? I know you are more familiar with templating. Do you think this is a good idea?
#69

### CODE REVIEW

**Comment by bepetersn** [comment]
Hey Wil, this looks like a pretty good idea, what you have here. I love how much simpler it is inside the templates. It was smart to hard-code the names into the templates, and work off of that, though. Simpler than some ways of doing it.

I wish it was backed with less funky-looking code in the "macros.html", but that's probably necessary for this kind of solution. I don't know. We'll see what Dave / others think.

**Comment by bepetersn** [comment]
Hey Wil, can you just tell me if this templating solution works in your local? If so, I'll merge it, because we need to keep moving and this is holding Sarah and I both up.

**Comment by wilbertom** [comment]
Yeah it works on my end

**Comment by bepetersn** [comment]
Hm. Well if no more input is forthcoming, I'm going to merge this, because it looks good to me. Unfortunately, your branch is now too out-of-sync to automatically merge. Worst case scenario, I will pick through what we want to push to the site tomorrow afternoon, and merge then.

**Comment by bepetersn** [comment]
OR: 

Maybe you could update your changes to work with Sarah's recent changes? Like I said, I'll get to it if not.

**Comment by bepetersn** [comment]
Hopefully, you've seen my pull request to your repo. I will need to review your code some more tomorrow to propose some more changes to make it fully compatible.

**Comment by sarahelizabeth** [comment]
Does this work? Can I merge this? I'm about to start editing the table again and I don't want to do it twice. @wilbertom @eads @bepetersn

**Comment by bepetersn** [comment]
No. Doesn't work, since we've changed stuff intermediately. It's a pain, but I wasn't able to get the chart template to work after these changes. I didn't devote enough time to it...

**Comment by sarahelizabeth** [comment]
Ok. I will just make the changes in the HTML and if I am able to finish all
my other tasks before we meet next Wednesday I will look into alternate
methods of templating.

**Comment by bepetersn** [comment]
Yeah, that's fine. I will try to get what I need to get done as well in time to look at it.

**Comment by bepetersn** [comment]
Hey, gonna close this, though I may still use it for inspiration when I come back to this eventually.

**Pull request closed without merging**
